In [15]:
#importing array for array operation
import array
#initializing array with array values
arr = array.array('l', [1,3,5,7,9,11,13])
#print(Original array)
print("Newly Created array: ")
for l in range (0,6):
  print (arr[l],end = " ")




Newly Created array: 
1 3 5 7 9 11 

In [17]:
import pandas as pd
#directory of lists
dict = {'name':["Honey","Shaurya","yadav","lamrin"],
'age':["28","39","34","36"]}
info = pd.DataFrame(dict, index =[True, True, False, True])
print(info)

          name age
True     Honey  28
True   Shaurya  39
False    yadav  34
True    lamrin  36


In [18]:
import pandas as pd
dict ={'name':["Honey","Shaurya","Yadav","Lamrin"],'age':["28","29","44,","45"]}
info = pd.DataFrame(dict, index = [True,True,False,True])
# accessing a dataframe using .loc
print(info.loc[True])

         name age
True    Honey  28
True  Shaurya  29
True   Lamrin  45


In [19]:
import numpy as np
arr = np.arange(16)
print("The Original array is: \n",arr)
arr =np.arange(16).reshape(8 ,2)
print("\nreshaped array: \n",arr)
# shape array with 2 r and 8 coloumns
arr = np.arange(16).reshape(8 ,2)
print("\nreshaped array: \n", arr)

The Original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

reshaped array: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
